name       : thonny
version    : 3.3.11
release    : 17
source     :
    - https://github.com/thonny/thonny/archive/v3.3.11.tar.gz : 449e4636aff1b23c04151b677ee05ea158fb0860a753852d4dcb98e838fb7167
homepage   : https://thonny.org
license    : MIT
component  : programming.ide
summary    : Python IDE for beginners
description: |
    Thonny is a simple Python IDE with features useful for learning programming. It comes with a debugger which is able to visualize all the conceptual steps taken to run a Python program (executing statements, evaluating expressions, maintaining the call stack). There is a GUI for installing 3rd-party packages and special mode for learning about references.
rundeps    :
    - pylint
    - python-asttokens
    - python-distro
    - python-docutils
    - python-mypy
    - python-pyserial
    - python-send2trash
    - python3-jedi
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 packaging/linux/org.thonny.Thonny.desktop $installdir/usr/share/applications/org.thonny.Thonny.desktop
    install -Dm00644 packaging/linux/thonny.1 $installdir/usr/share/man/man1/thonny.1
    install -Dm00644 packaging/linux/org.thonny.Thonny.appdata.xml $installdir/usr/share/metainfo/org.thonny.Thonny.appdata.xml

    # Installing icons
    for px in 16 22 32 48 64 128 192 256 ; do
        install -Dm00644 packaging/icons/thonny-${px}x${px}.png $installdir/usr/share/icons/hicolor/${px}x${px}/apps/thonny.png
    done
