name       : thonny
version    : 3.1.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/87/ba/a1cd77bcfdab52027bf946832585911ebac8f7871c665ac2a5f6e2e2fe54/thonny-3.1.2.tar.gz : 13dd3fc1f5150853904e1cec650c380e4ed27b8cc38e14938ef2522d0d41ba35
license    : MIT
component  : programming.ide
summary    : Python IDE for beginners
description: |
    Thonny is a simple Python IDE with features useful for learning programming. It comes with a debugger which is able to visualize all the conceptual steps taken to run a Python program (executing statements, evaluating expressions, maintaining the call stack). There is a GUI for installing 3rd-party packages and special mode for learning about references.
rundeps    :
    - pylint
    - python-astroid
    - python-asttokens
    - python-docutils
    - python-mypy_extensions
    - python-pyperclip
    - python-pyserial
    - python3-jedi
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $workdir/packaging/linux/org.thonny.Thonny.desktop $installdir/usr/share/applications/thonny.desktop
    install -D -m 00644 $workdir/packaging/icons/thonny-256x256.png $installdir/usr/share/pixmaps/thonny.png
