name       : thonny
version    : 3.2.7
release    : 10
source     :
    - https://github.com/thonny/thonny/archive/v3.2.7.tar.gz : 40ef47541cee14d744ebcd532e2c42d923fa2e31847e6772192d6d88b9bf808c
homepage   : https://thonny.org
license    : MIT
component  : programming.ide
summary    : Python IDE for beginners
description: |
    Thonny is a simple Python IDE with features useful for learning programming. It comes with a debugger which is able to visualize all the conceptual steps taken to run a Python program (executing statements, evaluating expressions, maintaining the call stack). There is a GUI for installing 3rd-party packages and special mode for learning about references.
rundeps    :
    - pylint
    - python-astroid
    - python-asttokens
    - python-docutils
    - python-mypy
    - python-pyperclip
    - python-pyserial
    - python-send2trash
    - python3-jedi
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 $workdir/thonny-$version/packaging/linux/org.thonny.Thonny.desktop $installdir/usr/share/applications/thonny.desktop
    install -Dm00644 $workdir/thonny-$version/packaging/icons/thonny-256x256.png $installdir/usr/share/pixmaps/thonny.png
