name       : thonny
version    : 3.0.8
release    : 1
source     :
    - https://files.pythonhosted.org/packages/e3/0a/3f0e0c29a16d4998094c1260e5f12f07ea58224aae7df2c354efdb93ba73/thonny-3.0.8.tar.gz : c5d6d9029e96cb24c6fbad36b61955fd05ad9ee742f1c8d99df35e87425c6fd4
license    : MIT
component  : editor
summary    : Python IDE for beginners
description: |
    Thonny is a simple Python IDE with features useful for learning programming.
    It comes with a debugger which is able to visualize all the conceptual steps
    taken to run a Python program (executing statements, evaluating expressions,
    maintaining the call stack). There is a GUI for installing 3rd party packages
    and special mode for learning about references.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
rundeps    :
    - pylint
    - python-docutils
    - python-mypy
    - python-pyperclip
    - python-pyserial
    - python3-jedi
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $workdir/packaging/linux/org.thonny.Thonny.desktop $installdir/usr/share/applications/thonny.desktop
    install -D -m 00644 $workdir/packaging/icons/thonny-256x256.png $installdir/usr/share/pixmaps/thonny.png
