name       : thonny
version    : 3.2.5
release    : 6
source     :
    - https://github.com/thonny/thonny/archive/v3.2.5.tar.gz : ca81bd7352aefe64d34001501da691398b66b19543f3a2b714e7356d2c418dbc
license    : MIT
component  : programming.ide
summary    : Python IDE for beginners
description: |
    Thonny is a simple Python IDE with features useful for learning programming. It comes with a debugger which is able to visualize all the conceptual steps taken to run a Python program (executing statements, evaluating expressions, maintaining the call stack). There is a GUI for installing 3rd-party packages and special mode for learning about references.
rundeps    :
    - pylint
    - python-astroid
    - python-asttokens
    - python-docutils
    - python-mypy_extensions
    - python-pyperclip
    - python-pyserial
    - python3-jedi
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $workdir/thonny-$version/packaging/linux/org.thonny.Thonny.desktop $installdir/usr/share/applications/thonny.desktop
    install -D -m 00644 $workdir/thonny-$version/packaging/icons/thonny-256x256.png $installdir/usr/share/pixmaps/thonny.png
