name       : thonny
version    : 3.2.1
release    : 4
source     :
    - https://github.com/thonny/thonny/archive/v3.2.1.tar.gz : 3aed28dbe0c93dc668b41aa72a4a14cc25ac14cd2a94a92a714522dd1a1c7a5a
license    : MIT
component  : programming.ide
summary    : Python IDE for beginners
description: |
    Thonny is a simple Python IDE with features useful for learning programming. It comes with a debugger which is able to visualize all the conceptual steps taken to run a Python program (executing statements, evaluating expressions, maintaining the call stack). There is a GUI for installing 3rd-party packages and special mode for learning about references.
rundeps    :
    - pylint
    - python-astroid
    - python-asttokens
    - python-docutils
    - python-mypy_extensions
    - python-pyperclip
    - python-pyserial
    - python3-jedi
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $workdir/thonny-$version/packaging/linux/org.thonny.Thonny.desktop $installdir/usr/share/applications/thonny.desktop
    install -D -m 00644 $workdir/thonny-$version/packaging/icons/thonny-256x256.png $installdir/usr/share/pixmaps/thonny.png
